### ISSUE TITLE
Output not generating

### ISSUE THREAD

**Issue by pangteydivesh** [mattmar/rasterdiv#1]
I used the Rao function on the NDVI image with a moving window of 3. It has been more than 5 days since the function running. Will the function generate output or it will keep going on like this. The NDVI image is of Sentinel-2 and covering around 500 km sq area.

![Screenshot (40)](https://user-images.githubusercontent.com/86014039/122875109-75607700-d351-11eb-859f-fca6977644bc.png)

**Comment by mattmar** [comment]
@pangteydivesh I'm afraid you have too many pixels to hope to have results in a reasonable time frame.
Try to work in parallel using the `Rao` option `np` or resample the raster at a coarser resolution.

**Comment by mattmar** [comment]
The issue was related to some user's computational limitations and not to the algorithm.
