### ISSUE TITLE
Apply Rao's Q to Sampling Grid 

### ISSUE THREAD

**Issue by sascaggs** [mattmar/rasterdiv#3]
I have a RasterLayer that contains NDVI values and I have a sampling grid as a SpatialPolygonsDataFrame. Here are the details of those two objects: 

`NDVI_ext`
class      : RasterLayer 
dimensions : 2716, 2880, 7822080  (nrow, ncol, ncell)
resolution : 3.125, 3.125  (x, y)
extent     : 270084.4, 279084.4, 1764175, 1772663  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=16 +datum=WGS84 +units=m +no_defs 
source     : memory
names      : layer 
values     : 0.4966216, 0.9459583  (min, max)

`NDVI_spdf`
class       : SpatialPolygonsDataFrame 
features    : 232 
extent      : 270084.4, 279084.4, 1764175, 1772663  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=16 +datum=WGS84 +units=m +no_defs 
variables   : 1
names       :  ID,
min values  :   1,          
max values  : 232,        

_I want to calculate Rao's Q inside each cell of the grid_ using the field "ID", analogous to the use of the "CONTINENT" field shown in the example vignette (https://mattmar.github.io/rasterdiv/articles/rasterdiv_area_based_Rao.html). But when I do this, I receive an error: 

`paRao( x=NDVI_ext, area=NDVI_spdf, field='ID', window=9 )`
Error in combn(p, m = 2, FUN = prod, na.rm = TRUE) : n < m

Is there a clear solution to this problem? I suspect there is an alternative approach in uses raster::extract to apply the `paRao` function to each sample unit in the grid, but it's not obvious how to do this either because of the moving window. 

Any advice about this issue would be helpful. I am also new to posting to Issues so if this is not the appropriate venue or format, do let me know.

**Comment by mattmar** [comment]
Hi Shane,
I've noticed only now your post, apologises.

This should be possible with rasterdiv, could you share both vector and raster so I can double check where the error is?

Best wishes,
Matteo

**Comment by mattmar** [comment]
Solved in version 0.3.2, closing it.
