### ISSUE TITLE
Rao Q Area based Multidimensional:  Error in utils::combn(length(tw[[1]]), 2) : n < m 

### ISSUE THREAD

**Issue by epatriarca1** [mattmar/rasterdiv#5]
Ciao! 

I am trying to compute Multidimensional Area based Rao´s Q Index on hyperspectral data with 30m pixels and I was interested in extracting the Rao´s Q within 7 plots of 90x90m size.

These are the characteristics of one of the bands I am using:
band3:
class : SpatRaster 
dimensions  : 456, 474, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent: 691430, 705650, 5144970, 5158650  (xmin, xmax, ymin, ymax)
coord. ref. : WGS 84 / UTM zone 32N (EPSG:32632) 
min value   : 1 
max value   : 26841

And this is the shapefile containing the 7 grids corresponding to my areas (the counterpart of the vector world of your vignette)
grid:
class : SpatVector 
 geometry : polygons 
 dimensions  : 7, 15  (geometries, attributes)
 extent : 696320, 703220, 5152770, 5154300  (xmin, xmax, ymin, ymax)
 coord. ref. : WGS 84 / UTM zone 32N (EPSG:32632) 
 names  :   fid        id      left       top     right    bottom mean5 nspecies5 meanrich SHANNON
 type   : <num>     <num>     <num>     <num>     <num>     <num> <num>     <num>    <num>   <num>
 values   :    46 1.073e+05 6.985e+05 5.153e+06 6.985e+05 5.153e+06     2         7     3.66    1.68

Even with the the latest version of the package (0.3.4) I was encountering this error:
I was trying to run:
RaoMC <-
  paRao_mod (
    x = c(band3, band57),
    area = grid,
    field = 'fid',
    alpha = 3,
    method = "multidimension"
  )
where fid corresponds to CONTINENT field of world vector in the vignettes.

But even with the latest version of the package (0.3.4) I was encountering this error:
Error in utils::combn(length(tw[[1]]), 2) : n < m

I modified this function (https://rdrr.io/github/mattmar/rasterdiv/src/R/mpaRaoAreaS.R), assuming that it would not work only with unique values, by adding these lines inside the function:
Rows 20-21:  crop1dt = cbind(crop1dt, rep(11, nrow(crop1dt)))
                     #print(crop1dt)
Rows 88:     tw = tw[-length(tw)]

Now the function pa.Rao runs! 
Running the so modified function on the vignette data for each continent gives the same results for each continent as with the original function. So, the function should work correctly.

Thank you very much,
Emanuela

**Comment by epatriarca1** [comment]
*Rows 80-81: crop1dt = cbind(crop1dt, rep(11, nrow(crop1dt)))

**Comment by mattmar** [comment]
Ciao Emanuela,

Thanks for spotting this. 

This bug was solved in the latest version of rasterdiv on GitHub, soon I'll send it to CRAN (version-to-be v0.3.5).

Matteo

**Comment by mattmar** [comment]
Ciao Emanuela,

Thanks for spotting this. 

This bug was solved in the latest version of rasterdiv on GitHub, soon I'll send it to CRAN (version-to-be v0.3.5).

Matteo
