### ISSUE TITLE
Rao´s Q Area based Multidimensional: same results for different input rasters

### ISSUE THREAD

**Issue by epatriarca1** [mattmar/rasterdiv#6]
Ciao!

Following this Issue #5 

Whatever combination of 150 bands I use, I always get the same results for each plot (0.009588546). I tried adjusting several parameters (simplify/rescale) but it did not work. 

I also changed the input raster, using vegetation indices. It did not work as well (whatever indices I use, I always get similar values 9.588546e-07).

Any advice?
Thank you very much,
Emanuela

**Comment by mattmar** [comment]
Ciao Emanuela,

Thanks for spotting this. 

This bug was solved in the latest version of rasterdiv on GitHub, soon I'll send it to CRAN (version-to-be v0.3.5).

Matteo
