### ISSUE TITLE
Error in utils::combn(p, m = 2, FUN = prod, na.rm = TRUE): n < m when applying Area-based Rao's Q

### ISSUE THREAD

**Issue by L00p-N1nja** [mattmar/rasterdiv#9]
Hi Matteo,

I am trying to compute the Area-based Rao's Q for 30 islands, but I encountered the same error as described in issue [#8](https://github.com/mattmar/rasterdiv/issues/8). Below is the code I used:
<pre>```r
library(terra)
library(rasterdiv)

island <- vect("GIS/island.shp")
island
# Output:
# class       : SpatVector 
# geometry    : polygons 
# dimensions  : 30, 2  (geometries, attributes)
# extent      : 117.3159, 120.3906, 23.56712, 26.9712  (xmin, xmax, ymin, ymax)
# source      : island.shp
# coord. ref. : lon/lat WGS 84 (EPSG:4326) 
# names       :        NAME   AREA
# type        :       <chr>  <num>
# values      : Dongshandao  220.5
#               Tayu 0.8311
#               Duimianyu 0.1059

NDVI <- rast("GIS/NDVI/NDVI_REPROJ_MERGED.tif")
NDVI
# class       : SpatRaster 
# dimensions  : 48799, 43437, 1  (nrow, ncol, nlyr)
# resolution  : 9.433864e-05, 9.433864e-05  (x, y)
# extent      : 116.9998, 121.0976, 23.40819, 28.01182  (xmin, xmax, ymin, ymax)
# coord. ref. : lon/lat WGS 84 (EPSG:4326) 
# source      : NDVI_REPROJ_MERGED.tif 
# name        : NDVI_REPROJ_MERGED 
# min value   : -1 
# max value   : 1```</pre>

While processing the Area-based Rao's index, I get the following error:
```r
RaoC <- paRao(x=NDVI, area=island, field='NAME', alpha=c(1,2))
Processing area-based Rao's index.
Processing area-based Rao's index.
Error in utils::combn(p, m = 2, FUN = prod, na.rm = TRUE): n < m```</pre>

Could you please help me resolve this issue?

**Comment by mattmar** [comment]
Hi @L00p-N1nja , be sure to use rasterdiv 0.3.6, as I've solved this bug in this version . If the bug persist, let me know and I'll help you solving it.

**Comment by L00p-N1nja** [comment]
Hi @mattmar , the package version check shows that the rasterdiv version is 0.3.6. Below is the code I used:
```r
# Version check
packageVersion("rasterdiv")
[1] ‘0.3.6’

```
I am still encountering the issue mentioned above. What should I do next?

**Comment by mattmar** [comment]
@L00p-N1nja I see, you are using area-based Rao. It should be now fixed on the Github version, see below: 

```
test <- terra::rast(matrix(c(1,1,1,1,1,1,1,1,1),ncol=3),ext=c(0,1,0,1))

testP <- terra::as.polygons(terra::ext(test))
testP$id=1

terra::plot(test)
terra::plot(testP, add=T, lwd=5)

rasterdiv::paRao(x=test, area=testP, field='id', alpha=c(1,2))

```
let me know if you still have problems with this

**Comment by L00p-N1nja** [comment]
@mattmar , I've reinstalled the version from GitHub, and the error is no longer appearing. However, I got alpha.1 and alpha.2 as NA, which has also occurred in my work. How should I handle this situation?
```r
> rm(list=ls())
> test <- terra::rast(matrix(c(1,1,1,1,1,1,1,1,1),ncol=3),ext=c(0,1,0,1))
> testP <- terra::as.polygons(terra::ext(test))
> testP$id=1
> terra::plot(test)
> terra::plot(testP, add=T, lwd=5)
> rasterdiv::paRao(x=test, area=testP, field='id', alpha=c(1,2))
Processing area-based Rao's index.
Processing area-based Rao's index.
 class       : SpatVector 
 geometry    : polygons 
 dimensions  : 1, 3  (geometries, attributes)
 extent      : 0, 1, 0, 1  (xmin, xmax, ymin, ymax)
 coord. ref. :  
 names       :    id alpha.1 alpha.2
 type        : <num>   <chr>   <chr>
 values      :     1      NA      NA
Warnings:
In rasterdiv::paRao(x = test, area = testP, field = "id", alpha = c(1,  :
  Simplify=0. Rounding data to 0 decimal places.


> # Version check
> packageVersion("rasterdiv")
[1] ‘0.3.6’
> # load package
> library(rasterdiv)
> library(terra)
terra 1.7.83
> # load 30 islands shape file
> islands_poly <- vect("GIS/Islands_poly.shp")
Warnings:
[vect] Z coordinates ignored 
> islands_poly
 class       : SpatVector 
 geometry    : polygons 
 dimensions  : 30, 2  (geometries, attributes)
 extent      : 117.3159, 120.3906, 23.56712, 26.9712  (xmin, xmax, ymin, ymax)
 source      : Islands_poly.shp
 coord. ref. : lon/lat WGS 84 (EPSG:4326) 
 names       :        NAME   AREA
 type        :       <chr>  <num>
 values      : Dongshandao  220.5
                      Tayu 0.8311
                 Duimianyu 0.1059
> # load ndvi raster file
> ndvi_raster <- rast("GIS/NDVI/NDVI_REPROJ_MERGED.tif")
> ndvi_raster
class       : SpatRaster 
dimensions  : 48799, 43437, 1  (nrow, ncol, nlyr)
resolution  : 9.433864e-05, 9.433864e-05  (x, y)
extent      : 116.9998, 121.0976, 23.40819, 28.01182  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : NDVI_REPROJ_MERGED.tif 
name        : NDVI_REPROJ_MERGED 
min value   :                 -1 
max value   :                  1 
> # Compute Area based Rao’s Index
> RaoC <- paRao(x=ndvi_raster, area=islands_poly, field='NAME', alpha=c(1,2))
Processing area-based Rao's index.
Processing area-based Rao's index.
Warnings:
In paRao(x = ndvi_raster, area = islands_poly, field = "NAME", alpha = c(1,  :
  Simplify=0. Rounding data to 0 decimal places.
> RaoC$alpha.1
 [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[30] NA

**Comment by L00p-N1nja** [comment]
It works perfectly for me, thanks! @mattmar
